import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker

# Load .csv data generated by 01_churn_overview.sql, 02_churn_reasons.sql, and 03_churn_by_month.sql
overview = pd.read_csv('../data/raw/01_churn_overview.csv')
reasons = pd.read_csv('../data/raw/02_churn_reasons.csv')
monthly = pd.read_csv('../data/raw/03_churn_by_month.csv')
monthly['churn_month'] = pd.to_datetime(monthly['churn_month'])

# Excluding no_data because it's a data gap rather than an actual churn reason
reasons_known = reasons[reasons['reason_code'] != 'no_data'].copy()
reasons_known = reasons_known.sort_values('lost_mrr', ascending=True)

# Donut chart showing the proportion of active and churned accounts
fig0, ax0 = plt.subplots(figsize=(8, 8))

values = [active, churned]
labels = ['Active', 'Churned']
colors = ['#4285F4', '#e05c5c']

wedges, texts, autotexts = ax0.pie(
    values,
    labels=labels,
    colors=colors,
    autopct='%1.0f%%',
    startangle=90,
    wedgeprops=dict(width=0.5),
    pctdistance=0.75
)
for autotext in autotexts:
    autotext.set_fontweight('bold')
    autotext.set_fontsize(10)

# Total accounts label
ax0.text(0, 0.1, 'Total Accounts', ha='center', va='center',
         fontsize=12, color='gray')
ax0.text(0, -0.05, '500', ha='center', va='center',
         fontsize=28, fontweight='bold', color='#333333')

ax0.set_title('Account Status Overview', fontsize=13)
plt.tight_layout()
plt.savefig('../data/outputs/01_account_status_overview.png', dpi=150, bbox_inches='tight')
plt.show()

# Horizontal bar chart showing the lost MRR by churn reason
fig1, ax1 = plt.subplots(figsize=(8, 6))
ax1.barh(reasons_known['reason_code'], reasons_known['lost_mrr'], color='#4285F4')
ax1.set_title('Lost MRR by Churn Reason', fontsize=13)
ax1.set_xlabel('Lost MRR (USD)')
ax1.set_ylabel('Churn Reason Code')
ax1.xaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'${x:,.0f}'))
ax1.set_xlim(0, reasons_known['lost_mrr'].max() * 1.1)
for i, val in enumerate(reasons_known['lost_mrr']):
    ax1.text(val + 800, i, f'${val:,.0f}', va='center', fontsize=9)
plt.tight_layout()
plt.savefig('../data/outputs/02_lost_mrr_by_churn_reason_code.png', dpi=150, bbox_inches='tight')
plt.show()

# Line chart showing the number of churned accounts by month
fig2, ax2 = plt.subplots(figsize=(8, 6))
ax2.plot(monthly['churn_month'], monthly['churned_accounts'],
         marker='o', color='#4285F4', linewidth=2)
ax2.fill_between(monthly['churn_month'], monthly['churned_accounts'], alpha=0.15, color='#72a4f7')
ax2.set_title('Churned Accounts by Month', fontsize=13)
ax2.set_xlabel('Month')
ax2.set_ylabel('Churned Accounts')
ax2.tick_params(axis='x', rotation=45)
plt.tight_layout()
plt.savefig('../data/outputs/03_churned_accounts_by_month.png', dpi=150, bbox_inches='tight')
plt.show()
